#!/bin/bash
#Check for GPGPUSIM_ROOT
if [ -z ${GPGPUSIM_ROOT} ]; then echo "Please set GPGPU-SIM environment variables"; exit; fi

#Check for simulation architecture
GPU_ARCH=GTX480
if [ -z ${1} ]; then echo "GTX480 is set as default architecture for runnig on GPGPU-SIM"; else GPU_ARCH=$1; fi

#Check for BIDIR and create it in case it does not exist
BINDIR=compute/bin
if [ ! -d "$BINDIR" ]; then
    # BINDIR does no exist
    mkdir bin
    if [ ! -d "$BINDIR/release" ]; then
        # release does no exist
        mkdir compute/bin/release
    fi
fi

#Copy GPGPU-SIM GPU_ARCH config file for simulation
cp $GPGPUSIM_ROOT/configs/$GPU_ARCH/* $BINDIR/release/
